# Generated by Django 5.0 on 2023-12-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_contactdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default', max_length=50)),
                ('jobname', models.CharField(max_length=50)),
                ('location', models.CharField()),
                ('l_skills', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
