# Generated by Django 5.0 on 2023-12-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_workdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default', max_length=50)),
                ('servicename', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
