# Generated by Django 5.0 on 2023-12-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_educationdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='ImagesForHomepage')),
                ('htmlid', models.CharField(max_length=50)),
                ('href', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('link', models.URLField()),
            ],
        ),
    ]
