# Generated by Django 5.0 on 2023-12-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_projectdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default', max_length=50)),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('github', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('whatsapp', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
    ]
